@url = http://localhost:5000/tracker/expenses
@admin_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwOWJjNTAyZS02NzJlLTQxZmEtOWUzYy1mYThiNjA5ODk3YTYiLCJ1c2VybmFtZSI6Im5hZ2Fzcml0aGEiLCJ1c2VySW1hZ2VVcmwiOiJodHRwczovL3Jlcy1jb25zb2xlLmNsb3VkaW5hcnkuY29tL2R0eWlvbWt0cC9tZWRpYV9leHBsb3Jlcl90aHVtYm5haWxzLzRhNDA5YTgwZjA2N2NiNzY3NzlmMzY5MTY3MTFlYzY4L2RldGFpbGVkIiwiZW1haWwiOiJuYWdhc3JpdGhhLmVyQGc3Y3IuY29tIiwicm9sZSI6ImFkbWluIiwiY3JlYXRlZEF0IjoiMjAyNC0xMC0yNVQxMjoyMzo1Mi4wOTRaIiwidXBkYXRlZEF0IjoiMjAyNC0xMC0yNVQxMjoyMzo1Mi4wOTRaIiwiaWF0IjoxNzI5ODU5ODc4LCJleHAiOjE3MzAxMTkwNzh9.mJbwW1z4baq4ddgjVsM_7co84L2fqmC9TpRYlR48EYs
GET {{url}}
Accept: application/json
Authorization: Bearer {{admin_token}}
###

GET {{url}}/4d1c9059-989c-423d-9fd1-7c3fd2621593
Accept: application/json
Authorization: Bearer {{admin_token}}
###

//to fetch expenses from start-date to end date
GET {{url}}?startDate=2024-1-01&endDate=2024-10-14
Authorization: Bearer {{admin_token}}
###



//to fetch the data related to the category
GET {{url}}?filter=Saree
Accept: application/json
Authorization : Bearer {{admin_token}}
###

POST  {{url}}
Content-type:application/json
Authorization: Bearer {{admin_token}}

{
    "amount" : 10,
    "date": "2024-04-10",
    "name": "Marrage shopping",
    "category": "Shopping",
    "transaction_type": "expense",
    "currency": "INR"
    //"description": "it is for testing purpose"
}

###

//to update the db
PUT {{url}}/4d1c9059-989c-423d-9fd1-7c3fd2621593
Content-Type: application/json
Authorization: Bearer {{admin_token}}

{
    "date" : "2024-10-12",
    "category" : "Saree" 
}
###

//to delete the column
DELETE {{url}}/3353b48e-ee37-4c70-8469-25d856c7fab0
Authorization: Bearer {{admin_token}}
###

GET {{url}}/filter/group-by-date?offset=0
Authorization: Bearer {{admin_token}}
###

GET {{url}}/filter/group-by-category?startDate=2024-01-01&endDate=2024-12-12
Authorization: Bearer {{admin_token}}

###

GET {{url}}/filter/group-by-category
Authorization: Bearer {{admin_token}}
###

GET {{url}}/filter/group-by-week?month=1
Authorization: Bearer {{admin_token}}
###

GET {{url}}/filter/group-by-month
Authorization: Bearer {{admin_token}}
###

# GET {{url}}/filter/group-by-year
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwYjIxOTA4Yi1iNTVmLTQ3YjUtYjMzZi1jN2Y0ZWJlNjFiNTMiLCJ1c2VybmFtZSI6InZhbXNpY2giLCJ1c2VySW1hZ2VVcmwiOm51bGwsImVtYWlsIjoibmFnYXNhaS52YW1zaUBnN2NyLmNvbSIsInJvbGUiOiJ1c2VyIiwiY3JlYXRlZEF0IjoiMjAyNC0xMC0xNlQxMjo0OTo1MS40MDZaIiwidXBkYXRlZEF0IjoiMjAyNC0xMC0xNlQxMjo0OTo1MS40MDZaIiwiaWF0IjoxNzI5MzQ4NDkzLCJleHAiOjE3Mjk0MzQ4OTN9.woVBH_u-S9GKdTX8ZUdEwxUI_o3oOldfepI9-jupuyU
