@url = http://localhost:5000/users/0b21908b-b55f-47b5-b33f-c7f4ebe61b53/expenses

//to fetch all details
GET {{url}}/
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwYjIxOTA4Yi1iNTVmLTQ3YjUtYjMzZi1jN2Y0ZWJlNjFiNTMiLCJ1c2VybmFtZSI6InZhbXNpY2giLCJ1c2VySW1hZ2VVcmwiOm51bGwsImVtYWlsIjoibmFnYXNhaS52YW1zaUBnN2NyLmNvbSIsInJvbGUiOiJ1c2VyIiwiY3JlYXRlZEF0IjoiMjAyNC0xMC0xNlQxMjo0OTo1MS40MDZaIiwidXBkYXRlZEF0IjoiMjAyNC0xMC0xNlQxMjo0OTo1MS40MDZaIiwiaWF0IjoxNzI5MjI3NzA2LCJleHAiOjE3MjkyMzEzMDZ9.NOwqLXNRCRRJhlo1c77dps4hupYtAnIgejOakqkKbCc
###

GET {{url}}/0a421d2c-1a2c-4f9b-8315-62c850c4a2a7
Accept: application/json
###

//to fetch expenses from start-date to end date
GET {{url}}?startDate=2024-10-01&endDate=2024-10-14
###

//to fetch the data related to the category
GET {{url}}?filter=Transport
Accept: application/json
###

POST  http://localhost:5000/users/0b21908b-b55f-47b5-b33f-c7f4ebe61b53/expenses
Content-type:application/json

{
    "user_id" : "0b21908b-b55f-47b5-b33f-c7f4ebe61b53",
    "amount" : 10000,
    "date" : "2024-9-13",
    "name" : "Kukke trip",
    "category" : "Transport"
}
###

//to update the db
PUT {{url}}/63893475-3947-4ba7-974c-095c2fa01de5
Content-Type: application/json

{
    "date" : "2024-10-12"
}
###

//to delete the column
DELETE {{url}}/63893475-3947-4ba7-974c-095c2fa01de5
###

GET {{url}}/filter/group-by-date?offset=0
###

GET {{url}}/filter/group-by-category?startDate=2024-9-11&endDate=2024-10-07
###

GET {{url}}/filter/group-by-category?file_id=9344874e-5f5b-4083-a919-cdf3d298f117
###

GET {{url}}/filter/group-by-week?file_id=9344874e-5f5b-4083-a919-cdf3d298f117
###

GET {{url}}/filter/group-by-month
###

GET {{url}}/filter/group-by-year