@url = http://localhost:5000/expenses/categories
@user_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwYjIxOTA4Yi1iNTVmLTQ3YjUtYjMzZi1jN2Y0ZWJlNjFiNTMiLCJ1c2VybmFtZSI6InZhbXNpY2giLCJ1c2VySW1hZ2VVcmwiOm51bGwsImVtYWlsIjoibmFnYXNhaS52YW1zaUBnN2NyLmNvbSIsInJvbGUiOiJ1c2VyIiwiY3JlYXRlZEF0IjoiMjAyNC0xMC0xNlQxMjo0OTo1MS40MDZaIiwidXBkYXRlZEF0IjoiMjAyNC0xMC0xNlQxMjo0OTo1MS40MDZaIiwiaWF0IjoxNzI5NDg3MzM1LCJleHAiOjE3Mjk1NzM3MzV9.ZZNMEVA7G6v_4uB6WbS7qrAwOju0XZMUhtI16jl1Oao
@admin_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzZDU2YTg1Yy02OTQ4LTQ2ZWUtODBhYy04MWI5YmZlYmUxNTIiLCJ1c2VybmFtZSI6IkUgUiBOYWdhc3JpdGhhIiwidXNlckltYWdlVXJsIjpudWxsLCJlbWFpbCI6Im5hZ2Fzcml0aGEuZXJAZzdjci5jb20iLCJyb2xlIjoiYWRtaW4iLCJjcmVhdGVkQXQiOiIyMDI0LTEwLTE2VDEyOjQwOjMxLjIwN1oiLCJ1cGRhdGVkQXQiOiIyMDI0LTEwLTE2VDEyOjQwOjMxLjIwN1oiLCJpYXQiOjE3Mjk0OTQwODEsImV4cCI6MTcyOTU4MDQ4MX0.q7jOnmF_MlI7PTMiWPyW9kmAk1NKGvV7K5y2R2jKFtg
GET {{url}}/
Authorization: Bearer {{user_token}}
###

GET {{url}}?name=Transport charges
Authorization: Bearer {{admin_token}}