@url = http://localhost:5000/expenses/categories
@user_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1MDZhMGJjMS01Y2U5LTQwZWMtYTMwYy1jZjA2NTllMGM1MmYiLCJ1c2VybmFtZSI6IlZhbXNpIiwidXNlckltYWdlVXJsIjoiIiwiZW1haWwiOiJuYWdhc2FpLnZhbXNpQGc3Y3IuY29tIiwicm9sZSI6InVzZXIiLCJjcmVhdGVkQXQiOiIyMDI0LTEwLTIxVDEzOjQ2OjI3LjM3MloiLCJ1cGRhdGVkQXQiOiIyMDI0LTEwLTIxVDEzOjQ2OjI3LjM3MloiLCJpYXQiOjE3Mjk1MTg0MDcsImV4cCI6MTcyOTYwNDgwN30.X8YIzPz8FY_3S53L_21TvE-dRBwYCLjbGbN1u_Eas40
@admin_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzZDU2YTg1Yy02OTQ4LTQ2ZWUtODBhYy04MWI5YmZlYmUxNTIiLCJ1c2VybmFtZSI6IkUgUiBOYWdhc3JpdGhhIiwidXNlckltYWdlVXJsIjpudWxsLCJlbWFpbCI6Im5hZ2Fzcml0aGEuZXJAZzdjci5jb20iLCJyb2xlIjoiYWRtaW4iLCJjcmVhdGVkQXQiOiIyMDI0LTEwLTE2VDEyOjQwOjMxLjIwN1oiLCJ1cGRhdGVkQXQiOiIyMDI0LTEwLTE2VDEyOjQwOjMxLjIwN1oiLCJpYXQiOjE3Mjk0OTQwODEsImV4cCI6MTcyOTU4MDQ4MX0.q7jOnmF_MlI7PTMiWPyW9kmAk1NKGvV7K5y2R2jKFtg
GET {{url}}/
Authorization: Bearer {{user_token}}
###

POST {{url}}
Authorization: Bearer {{user_token}}
content-type:application/json

{
    "name" : "Transport charge",
    "type" : "expense"
}
###

GET {{url}}?name=Transport charges
Authorization: Bearer {{admin_token}}