@url = http://localhost:5000/expenses/tags
@user_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1MDZhMGJjMS01Y2U5LTQwZWMtYTMwYy1jZjA2NTllMGM1MmYiLCJ1c2VybmFtZSI6IlZhbXNpIiwidXNlckltYWdlVXJsIjoiIiwiZW1haWwiOiJuYWdhc2FpLnZhbXNpQGc3Y3IuY29tIiwicm9sZSI6InVzZXIiLCJjcmVhdGVkQXQiOiIyMDI0LTEwLTIxVDEzOjQ2OjI3LjM3MloiLCJ1cGRhdGVkQXQiOiIyMDI0LTEwLTIxVDEzOjQ2OjI3LjM3MloiLCJpYXQiOjE3Mjk1MTg0MDcsImV4cCI6MTcyOTYwNDgwN30.X8YIzPz8FY_3S53L_21TvE-dRBwYCLjbGbN1u_Eas40


GET {{url}}
Authorization: Bearer {{user_token}}
###

POST {{url}}/099c6bc6-6224-443b-a314-86f69f217c7f
Authorization: Bearer {{user_token}}
Content-Type: application/json

{
    "tag_name" : "sample tag"
}
###
PUT {{url}}/2dbeb4fa-d321-4f83-9853-d37afc0f8027
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwYjIxOTA4Yi1iNTVmLTQ3YjUtYjMzZi1jN2Y0ZWJlNjFiNTMiLCJ1c2VybmFtZSI6InZhbXNpY2giLCJ1c2VySW1hZ2VVcmwiOm51bGwsImVtYWlsIjoibmFnYXNhaS52YW1zaUBnN2NyLmNvbSIsInJvbGUiOiJ1c2VyIiwiY3JlYXRlZEF0IjoiMjAyNC0xMC0xNlQxMjo0OTo1MS40MDZaIiwidXBkYXRlZEF0IjoiMjAyNC0xMC0xNlQxMjo0OTo1MS40MDZaIiwiaWF0IjoxNzI5MzQ4NDkzLCJleHAiOjE3Mjk0MzQ4OTN9.woVBH_u-S9GKdTX8ZUdEwxUI_o3oOldfepI9-jupuyU
Content-Type: application/json

{
    "tag_name" : "sample"
}
###

DELETE {{url}}/2dbeb4fa-d321-4f83-9853-d37afc0f8027
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwYjIxOTA4Yi1iNTVmLTQ3YjUtYjMzZi1jN2Y0ZWJlNjFiNTMiLCJ1c2VybmFtZSI6InZhbXNpY2giLCJ1c2VySW1hZ2VVcmwiOm51bGwsImVtYWlsIjoibmFnYXNhaS52YW1zaUBnN2NyLmNvbSIsInJvbGUiOiJ1c2VyIiwiY3JlYXRlZEF0IjoiMjAyNC0xMC0xNlQxMjo0OTo1MS40MDZaIiwidXBkYXRlZEF0IjoiMjAyNC0xMC0xNlQxMjo0OTo1MS40MDZaIiwiaWF0IjoxNzI5MzQ4NDkzLCJleHAiOjE3Mjk0MzQ4OTN9.woVBH_u-S9GKdTX8ZUdEwxUI_o3oOldfepI9-jupuyU



