@url = http://localhost:5000/expenses/tags
@user_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0ZTRmYjNmMC0zMDFiLTQ4YTQtOGU2NS1jMTE2MGU4MmFlYTciLCJ1c2VybmFtZSI6ImphaG5hdmkiLCJ1c2VySW1hZ2VVcmwiOiJodHRwczovL3Jlcy1jb25zb2xlLmNsb3VkaW5hcnkuY29tL2R0eWlvbWt0cC9tZWRpYV9leHBsb3Jlcl90aHVtYm5haWxzLzRhNDA5YTgwZjA2N2NiNzY3NzlmMzY5MTY3MTFlYzY4L2RldGFpbGVkIiwiZW1haWwiOiJwZW5uYWJhZGkuamFobmF2aUBnN2NyLmNvbSIsInJvbGUiOiJ1c2VyIiwiY3JlYXRlZEF0IjoiMjAyNC0xMC0yNVQxMjoyNTowNC4zMDVaIiwidXBkYXRlZEF0IjoiMjAyNC0xMC0yNVQxMjoyNTowNC4zMDVaIiwiaWF0IjoxNzI5ODU5Mjg0LCJleHAiOjE3MzAxMTg0ODR9.KmeQCqhCpfIeRtl9JCxPdtPaQusrOsiuHm4pbvd6TXg

GET {{url}}
Authorization: Bearer {{user_token}}
###

POST {{url}}/3353b48e-ee37-4c70-8469-25d856c7fab0
Authorization: Bearer {{user_token}}
Content-Type: application/json

{
    "tag_name" : "sample"
}
###
PUT {{url}}/cdee2832-6315-4796-9942-e8a5fe1991d8
Authorization: Bearer {{user_token}}
Content-Type: application/json

{
    "tag_name" : "sample"
}
###

DELETE {{url}}/cdee2832-6315-4796-9942-e8a5fe1991d8
Authorization: Bearer {{user_token}}


