@url = http://localhost:5000/users/0b21908b-b55f-47b5-b33f-c7f4ebe61b53/files

GET {{url}}
Accept: application/json
###

DELETE {{url}}/delete/1463fd5e-7982-42aa-9d43-c3a47da77bb1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwYjIxOTA4Yi1iNTVmLTQ3YjUtYjMzZi1jN2Y0ZWJlNjFiNTMiLCJ1c2VybmFtZSI6InZhbXNpY2giLCJ1c2VySW1hZ2VVcmwiOm51bGwsImVtYWlsIjoibmFnYXNhaS52YW1zaUBnN2NyLmNvbSIsInJvbGUiOiJ1c2VyIiwiY3JlYXRlZEF0IjoiMjAyNC0xMC0xNlQxMjo0OTo1MS40MDZaIiwidXBkYXRlZEF0IjoiMjAyNC0xMC0xNlQxMjo0OTo1MS40MDZaIiwiaWF0IjoxNzI5MzQ4NDkzLCJleHAiOjE3Mjk0MzQ4OTN9.woVBH_u-S9GKdTX8ZUdEwxUI_o3oOldfepI9-jupuyU
