@token =  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwOWJjNTAyZS02NzJlLTQxZmEtOWUzYy1mYThiNjA5ODk3YTYiLCJ1c2VybmFtZSI6Im5hZ2Fzcml0aGEiLCJ1c2VySW1hZ2VVcmwiOiJodHRwczovL3Jlcy1jb25zb2xlLmNsb3VkaW5hcnkuY29tL2R0eWlvbWt0cC9tZWRpYV9leHBsb3Jlcl90aHVtYm5haWxzLzRhNDA5YTgwZjA2N2NiNzY3NzlmMzY5MTY3MTFlYzY4L2RldGFpbGVkIiwiZW1haWwiOiJuYWdhc3JpdGhhLmVyQGc3Y3IuY29tIiwicm9sZSI6ImFkbWluIiwiY3JlYXRlZEF0IjoiMjAyNC0xMC0yNVQxMjoyMzo1Mi4wOTRaIiwidXBkYXRlZEF0IjoiMjAyNC0xMC0yNVQxMjoyMzo1Mi4wOTRaIiwiaWF0IjoxNzI5ODU5ODc4LCJleHAiOjE3MzAxMTkwNzh9.mJbwW1z4baq4ddgjVsM_7co84L2fqmC9TpRYlR48EYs

GET http://localhost:5000/users
Authorization: Bearer {{token}}
###

POST http://localhost:5000/users/register
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "username":"jahnavi",
    "email":"pennabadi.jahnavi@g7cr.com",
    "userImageUrl": "https://res-console.cloudinary.com/dtyiomktp/media_explorer_thumbnails/4a409a80f067cb76779f36916711ec68/detailed",
    "role":"user"
}

###
PUT http://localhost:5000/users/update/75a46297-de15-4a66-b155-767424b2b4a9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjNDg0YTJhYi1lOTIzLTQyM2MtOGM3YS01ZGU4NWRjODUxOTMiLCJ1c2VybmFtZSI6IkJlbm55IiwidXNlckltYWdlVXJsIjpudWxsLCJlbWFpbCI6ImpvaG4uYmVubnlAZzdjci5jb20iLCJyb2xlIjoiYWRtaW4iLCJjcmVhdGVkQXQiOiIyMDI0LTEwLTE0VDEyOjUxOjE0LjcwOFoiLCJ1cGRhdGVkQXQiOiIyMDI0LTEwLTE0VDEyOjU4OjU3LjQwOFoiLCJpYXQiOjE3Mjg5MTEzOTcsImV4cCI6MTcyODkxNDk5N30.YSnvOoD-Tyhmx6VRMEJt1oMaUd1wSJCUr_onyMGkcYk
Content-Type: application/json

{
    "userImageUrl": "https://wallpapercave.com/wp/wp5720440.jpg"
}


###
DELETE http://localhost:5000/users/remove/4e4fb3f0-301b-48a4-8e65-c1160e82aea7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhZjZjODNlOC0wZDdlLTQ4NWMtOTQ3ZC1lMTNjMTQwYmQ4NDAiLCJ1c2VybmFtZSI6IlZhbXNpIiwidXNlckltYWdlVXJsIjpudWxsLCJlbWFpbCI6Im5hZ2FzYWkudmFtc2lAZzdjci5jb20iLCJyb2xlIjoiYWRtaW4iLCJjcmVhdGVkQXQiOiIyMDI0LTEwLTE0VDE2OjU0OjIzLjQyM1oiLCJ1cGRhdGVkQXQiOiIyMDI0LTEwLTE0VDE2OjU0OjIzLjQyM1oiLCJpYXQiOjE3MjkwMjMxODEsImV4cCI6MTcyOTAyNjc4MX0.86WO88d3BO4rLXpJm9IZtUjcfs5r41DOYie6VFVFrlU