GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwZTg4Y2VkYi1iYzMzLTRiMWUtOGI2Ni0zYWM4OTY5YWIzMjAiLCJ1c2VybmFtZSI6IkUgTmFnYXNyaXRoYSIsInVzZXJJbWFnZVVybCI6bnVsbCwiZW1haWwiOiJuYWdhc3JpdGhhLmVyQGc3Y3IuY29tIiwicm9sZSI6ImFkbWluIiwiY3JlYXRlZEF0IjoiMjAyNC0xMC0xNVQwNzoyOToyNS41ODRaIiwidXBkYXRlZEF0IjoiMjAyNC0xMC0xNVQwNzoyOToyNS41ODRaIiwiaWF0IjoxNzI4OTc3NDIzLCJleHAiOjE3Mjg5ODEwMjN9.2UDf4oJo38k1Tz-UZFjpqav4UT3fj0hTMXpD93Ml7ec
###

POST http://localhost:5000/users
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjNDg0YTJhYi1lOTIzLTQyM2MtOGM3YS01ZGU4NWRjODUxOTMiLCJ1c2VybmFtZSI6IkJlbm55IiwidXNlckltYWdlVXJsIjpudWxsLCJlbWFpbCI6ImpvaG4uYmVubnlAZzdjci5jb20iLCJyb2xlIjoiYWRtaW4iLCJjcmVhdGVkQXQiOiIyMDI0LTEwLTE0VDEyOjUxOjE0LjcwOFoiLCJ1cGRhdGVkQXQiOiIyMDI0LTEwLTE0VDEyOjU4OjU3LjQwOFoiLCJpYXQiOjE3Mjg5MTEzOTcsImV4cCI6MTcyODkxNDk5N30.YSnvOoD-Tyhmx6VRMEJt1oMaUd1wSJCUr_onyMGkcYk
Content-Type: application/json

{
    "username":"E R Nagasritha",
    "email":"nagasritha.er@g7cr.com",
    "role":"user"
}

###
DELETE http://localhost:5000/users/remove/0e88cedb-bc33-4b1e-8b66-3ac8969ab320